# Generated by Django 4.2.27 on 2026-02-01 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_booking_booking_status_alter_payment_status'),
        ('chat', '0002_alter_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='app.booking'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
