# Generated by Django 4.2.27 on 2026-02-01 09:23

from django.conf import settings
from django.db import migrations


def merge_duplicate_conversations(apps, schema_editor):
    """Gộp các conversation trùng host+guest, giữ lại conversation có id nhỏ nhất."""
    Conversation = apps.get_model('chat', 'Conversation')
    Message = apps.get_model('chat', 'Message')
    
    # Tìm các cặp host+guest bị trùng
    from django.db.models import Count
    duplicates = (
        Conversation.objects
        .values('host_id', 'guest_id')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    
    for dup in duplicates:
        host_id = dup['host_id']
        guest_id = dup['guest_id']
        
        # Lấy tất cả conversation của cặp này, sắp xếp theo id
        convs = list(Conversation.objects.filter(
            host_id=host_id, guest_id=guest_id
        ).order_by('id'))
        
        if len(convs) > 1:
            # Giữ lại conversation đầu tiên (id nhỏ nhất)
            main_conv = convs[0]
            
            # Di chuyển tất cả messages từ các conversation khác sang conversation chính
            for conv in convs[1:]:
                Message.objects.filter(conversation=conv).update(conversation=main_conv)
                # Xóa conversation trùng
                conv.delete()


def reverse_merge(apps, schema_editor):
    """Không thể reverse được vì đã xóa dữ liệu."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_conversation_booking_message_is_read'),
    ]

    operations = [
        # Bước 1: Gộp các conversation trùng
        migrations.RunPython(merge_duplicate_conversations, reverse_merge),
        
        # Bước 2: Thêm unique constraint
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('host', 'guest')},
        ),
        
        # Bước 3: Xóa cột booking
        migrations.RemoveField(
            model_name='conversation',
            name='booking',
        ),
    ]
