# Generated by Django 4.2.27 on 2025-12-17 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên tiện nghi')),
            ],
            options={
                'verbose_name': 'Tiện nghi',
                'verbose_name_plural': 'Tiện nghi',
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField(verbose_name='Ngày nhận')),
                ('check_out', models.DateField(verbose_name='Ngày trả')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền')),
                ('booking_status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy')], default='pending', max_length=10, verbose_name='Trạng thái đặt phòng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đơn đặt phòng',
                'verbose_name_plural': 'Đơn đặt phòng',
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Khóa chính')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá / đêm')),
                ('max_adults', models.IntegerField(verbose_name='Số người lớn')),
                ('max_children', models.IntegerField(default=0, verbose_name='Số trẻ em')),
                ('max_pets', models.IntegerField(default=0, verbose_name='Số thú cưng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Có hiển thị không')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Chủ nhà')),
            ],
            options={
                'verbose_name': 'Chỗ ở',
                'verbose_name_plural': 'Chỗ ở',
                'db_table': 'listings',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Điểm (1-5)')),
                ('comment', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app.booking')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá chỗ ở',
                'verbose_name_plural': 'Đánh giá chỗ ở',
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('media_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media_url', models.URLField(max_length=255, verbose_name='Link Media')),
                ('media_type', models.CharField(choices=[('image', 'Ảnh'), ('video', 'Video')], max_length=10, verbose_name='Loại media')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.review')),
            ],
            options={
                'verbose_name': 'Ảnh/Video đánh giá',
                'verbose_name_plural': 'Ảnh/Video đánh giá',
                'db_table': 'review_media',
            },
        ),
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('analysis_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sentiment', models.CharField(choices=[('positive', 'Tích cực'), ('negative', 'Tiêu cực'), ('neutral', 'Trung tính')], max_length=10, verbose_name='Cảm xúc')),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Độ tin cậy')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='app.review')),
            ],
            options={
                'verbose_name': 'Phân tích đánh giá AI',
                'verbose_name_plural': 'Phân tích đánh giá AI',
                'db_table': 'review_analyses',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=50, verbose_name='Phương thức')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại')], default='paid', max_length=10, verbose_name='Trạng thái thanh toán')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app.booking')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=255, verbose_name='Ảnh')),
                ('is_main', models.BooleanField(default=False, verbose_name='Ảnh đại diện')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.listing', verbose_name='Thuộc listing')),
            ],
            options={
                'verbose_name': 'Ảnh chỗ ở',
                'verbose_name_plural': 'Ảnh chỗ ở',
                'db_table': 'listing_images',
            },
        ),
        migrations.CreateModel(
            name='ListingAddress',
            fields=[
                ('address_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Khóa chính')),
                ('city', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận')),
                ('street', models.CharField(max_length=255, verbose_name='Đường')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.listing', verbose_name='Gắn với listing')),
            ],
            options={
                'verbose_name': 'Địa chỉ chỗ ở',
                'verbose_name_plural': 'Địa chỉ chỗ ở',
                'db_table': 'listing_addresses',
            },
        ),
        migrations.CreateModel(
            name='HostPolicy',
            fields=[
                ('policy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warning_count', models.IntegerField(default=0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chính sách chủ nhà',
                'verbose_name_plural': 'Chính sách chủ nhà',
                'db_table': 'host_policies',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Chưa giải quyết'), ('resolved', 'Đã giải quyết')], default='open', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='complaints', to='app.listing', verbose_name='Chỗ ở bị khiếu nại')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Người khiếu nại')),
            ],
            options={
                'verbose_name': 'Khiếu nại',
                'verbose_name_plural': 'Khiếu nại',
                'db_table': 'complaints',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='app.listing', verbose_name='Phòng'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Khách'),
        ),
        migrations.CreateModel(
            name='ListingAmenity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.amenity', verbose_name='Tiện nghi')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listing', verbose_name='Listing')),
            ],
            options={
                'verbose_name': 'Tiện nghi của chỗ ở',
                'verbose_name_plural': 'Tiện nghi của chỗ ở',
                'db_table': 'listing_amenities',
                'unique_together': {('listing', 'amenity')},
            },
        ),
    ]
