# Generated by Django 4.2.27 on 2025-12-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Khóa chính')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ tên người dùng')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email đăng nhập')),
                ('password', models.CharField(max_length=255, verbose_name='Mật khẩu đã hash')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('host', 'Chủ nhà'), ('guest', 'Khách hàng')], default='guest', max_length=10, verbose_name='Phân quyền')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT')),
                ('avatar_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ảnh đại diện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
