# Generated by assistant - add guests and payment fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=1, verbose_name='Số khách'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Chi tiết thanh toán (JSON)'),
        ),
    ]
