# Generated by Django 5.2.9 on 2025-12-23 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(related_name='listings', through='app.ListingAmenity', to='app.amenity'),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expired_at', models.DateTimeField(null=True)),
                ('verify_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xác thực',
                'verbose_name_plural': 'Xác thực',
                'db_table': 'verifications',
            },
        ),
    ]
