# Generated by assistant: ensure DB default for guests
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_guests_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=1, verbose_name='Số khách'),
        ),
    ]
