# Generated by Django 4.2.27 on 2025-12-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_remove_room_host_delete_review_delete_room'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
