# Generated by Django 5.2.9 on 2025-12-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_listing_checkin_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_created_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='reviewclassification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
