# Generated by Django 5.2.9 on 2025-12-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_guests_payment_fields'),
        ('app', '0008_remove_booking_booking_listing_checkin_idx_and_more'),
    ]

    operations = [
    ]
