# Generated by Django 5.2.9 on 2025-12-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_booking_guests_default'),
        ('app', '0009_merge_20251228_2230'),
    ]

    operations = [
    ]
