# Generated by Django 5.2.9 on 2025-12-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20251229_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='details',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
