# Generated by Django 4.2.27 on 2026-01-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_unused_payment_columns'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE bookings "
                        "ADD COLUMN IF NOT EXISTS base_price DECIMAL(10,2) NULL DEFAULT NULL"
                    ),
                    reverse_sql="ALTER TABLE bookings DROP COLUMN IF EXISTS base_price",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE bookings "
                        "ADD COLUMN IF NOT EXISTS cleaning_fee DECIMAL(10,2) NULL DEFAULT NULL"
                    ),
                    reverse_sql="ALTER TABLE bookings DROP COLUMN IF EXISTS cleaning_fee",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE bookings "
                        "ADD COLUMN IF NOT EXISTS guests INT NOT NULL DEFAULT 1"
                    ),
                    reverse_sql="ALTER TABLE bookings DROP COLUMN IF EXISTS guests",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE bookings "
                        "ADD COLUMN IF NOT EXISTS service_fee DECIMAL(10,2) NULL DEFAULT NULL"
                    ),
                    reverse_sql="ALTER TABLE bookings DROP COLUMN IF EXISTS service_fee",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE listings "
                        "ADD COLUMN IF NOT EXISTS cleaning_fee DECIMAL(10,2) NOT NULL DEFAULT 0"
                    ),
                    reverse_sql="ALTER TABLE listings DROP COLUMN IF EXISTS cleaning_fee",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE listings "
                        "ADD COLUMN IF NOT EXISTS extra_guest_fee DECIMAL(10,2) NULL DEFAULT NULL"
                    ),
                    reverse_sql="ALTER TABLE listings DROP COLUMN IF EXISTS extra_guest_fee",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE listings "
                        "ADD COLUMN IF NOT EXISTS weekend_multiplier DECIMAL(3,2) NOT NULL DEFAULT 1.00"
                    ),
                    reverse_sql="ALTER TABLE listings DROP COLUMN IF EXISTS weekend_multiplier",
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE payments "
                        "ADD COLUMN IF NOT EXISTS transaction_id VARCHAR(255) UNIQUE NULL"
                    ),
                    reverse_sql="ALTER TABLE payments DROP COLUMN IF EXISTS transaction_id",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='booking',
                    name='base_price',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá cơ bản'),
                ),
                migrations.AddField(
                    model_name='booking',
                    name='cleaning_fee',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Phí vệ sinh'),
                ),
                migrations.AddField(
                    model_name='booking',
                    name='guests',
                    field=models.IntegerField(default=1, verbose_name='Số khách'),
                ),
                migrations.AddField(
                    model_name='booking',
                    name='service_fee',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Phí dịch vụ'),
                ),
                migrations.AddField(
                    model_name='listing',
                    name='cleaning_fee',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Phí vệ sinh'),
                ),
                migrations.AddField(
                    model_name='listing',
                    name='extra_guest_fee',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Phí khách thêm/đêm'),
                ),
                migrations.AddField(
                    model_name='listing',
                    name='weekend_multiplier',
                    field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Hệ số cuối tuần'),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='transaction_id',
                    field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Mã giao dịch'),
                ),
            ],
        ),
    ]
