# Generated by Django on 2026-01-03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_booking_base_price_booking_cleaning_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_from',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu cho thuê'),
        ),
        migrations.AddField(
            model_name='listing',
            name='available_to',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc cho thuê'),
        ),
    ]
