# Generated by Django on 2026-01-03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_add_listing_available_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending','Chờ duyệt'),('approved','Đã duyệt'),('rejected','Từ chối')], default='pending', max_length=10, verbose_name='Trạng thái duyệt'),
        ),
    ]
