# Generated by Django 4.2.27 on 2026-01-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_add_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image_url',
            field=models.CharField(max_length=255, verbose_name='Ảnh'),
        ),
    ]
