# Generated by Django 4.2.27 on 2026-01-06 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_booking_booking_status'),
        ('app', '0018_alter_listingimage_image_url'),
    ]

    operations = [
    ]
