# Generated by Django 4.2.27 on 2026-01-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20260106_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='allow_parties',
            field=models.BooleanField(default=False, verbose_name='Cho phép tổ chức tiệc'),
        ),
        migrations.AddField(
            model_name='listing',
            name='allow_pets',
            field=models.BooleanField(default=False, verbose_name='Cho phép thú cưng'),
        ),
        migrations.AddField(
            model_name='listing',
            name='allow_smoking',
            field=models.BooleanField(default=False, verbose_name='Cho phép hút thuốc'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='Số phòng tắm'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Số phòng ngủ'),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.IntegerField(default=1, verbose_name='Số giường'),
        ),
        migrations.AddField(
            model_name='listing',
            name='cancellation_policy',
            field=models.CharField(choices=[('flexible', 'Linh hoạt'), ('moderate', 'Trung bình'), ('strict', 'Nghiêm ngặt')], default='moderate', max_length=20, verbose_name='Chính sách hủy'),
        ),
        migrations.AddField(
            model_name='listing',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ nhận phòng'),
        ),
        migrations.AddField(
            model_name='listing',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ trả phòng'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_co_detector',
            field=models.BooleanField(default=False, verbose_name='Máy phát hiện khí CO'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_fire_extinguisher',
            field=models.BooleanField(default=False, verbose_name='Bình chữa cháy'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_first_aid',
            field=models.BooleanField(default=False, verbose_name='Bộ sơ cứu'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_noise_monitor',
            field=models.BooleanField(default=False, verbose_name='Có máy đo độ ồn'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_security_camera',
            field=models.BooleanField(default=False, verbose_name='Có camera an ninh ngoài nhà'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_smoke_alarm',
            field=models.BooleanField(default=False, verbose_name='Máy báo khói'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_weapon',
            field=models.BooleanField(default=False, verbose_name='Có vũ khí tại chỗ ở'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_instant_book',
            field=models.BooleanField(default=False, verbose_name='Đặt phòng nhanh'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_self_checkin',
            field=models.BooleanField(default=False, verbose_name='Tự nhận phòng'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_superhost',
            field=models.BooleanField(default=False, verbose_name='Chủ nhà siêu cấp'),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Nhà riêng', 'Nhà riêng / nguyên căn'), ('Căn hộ', 'Căn hộ / chung cư'), ('Phòng riêng', 'Phòng riêng'), ('Biệt thự', 'Biệt thự'), ('Khách sạn / resort', 'Khách sạn / resort'), ('Nhà khách / nhà nghỉ', 'Nhà khách / nhà nghỉ'), ('Cabin / nhà gỗ', 'Cabin / nhà gỗ'), ('Tiny house', 'Tiny house'), ('Nhà trên cây', 'Nhà trên cây'), ('Nhà thuyền', 'Nhà thuyền'), ('Glamping / lều', 'Glamping / lều'), ('Nông trại / farmstay', 'Nông trại / farmstay')], default='Nhà riêng', max_length=50, verbose_name='Loại chỗ ở'),
        ),
        migrations.AddField(
            model_name='listing',
            name='usage_type',
            field=models.CharField(choices=[('Toàn bộ nhà', 'Toàn bộ nhà'), ('Phòng riêng', 'Phòng riêng'), ('Phòng chung', 'Phòng chung')], default='Toàn bộ nhà', max_length=50, verbose_name='Loại sử dụng'),
        ),
    ]
