# Generated by Django 4.2.27 on 2026-01-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_listing_allow_parties_listing_allow_pets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='allow_parties',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='allow_pets',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='allow_smoking',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='cancellation_policy',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='extra_guest_fee',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='has_co_detector',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='has_fire_extinguisher',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='has_first_aid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='has_smoke_alarm',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_instant_book',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_self_checkin',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_superhost',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='weekend_multiplier',
        ),
    ]
