# Generated by Django 4.2.27 on 2026-01-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_listing_allow_parties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('basic', 'Tiện nghi cơ bản'), ('featured', 'Tiện nghi nổi bật'), ('safety', 'An toàn')], default='basic', max_length=20, verbose_name='Loại'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon class (FontAwesome)'),
        ),
    ]
