# Generated by Django 4.2.27 on 2026-01-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_add_amenity_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='has_noise_monitor',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='has_security_camera',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='has_weapon',
        ),
    ]
