# Generated by Django 4.2.27 on 2026-01-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20260106_1528'),
        ('app', '0023_remove_safety_fields_from_listing'),
    ]

    operations = [
    ]
