# Generated by Django 4.2.27 on 2026-01-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_booking_booking_status_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='usage_type',
        ),
        migrations.RemoveField(
            model_name='reviewmedia',
            name='media_url',
        ),
        migrations.AddField(
            model_name='listing',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Phí vệ sinh'),
        ),
        migrations.AddField(
            model_name='listing',
            name='extra_guest_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Phí khách thêm/đêm'),
        ),
        migrations.AddField(
            model_name='listing',
            name='weekend_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Hệ số cuối tuần'),
        ),
        migrations.AddField(
            model_name='reviewmedia',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='media_type',
            field=models.CharField(max_length=10),
        ),
    ]
