# Generated by Django 4.2.27 on 2026-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_amenity_category_remove_amenity_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cleaning_fee',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='extra_guest_fee',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='weekend_multiplier',
        ),
        migrations.RemoveField(
            model_name='reviewmedia',
            name='media',
        ),
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('basic', 'Tiện nghi cơ bản'), ('featured', 'Tiện nghi nổi bật'), ('safety', 'An toàn')], default='basic', max_length=20, verbose_name='Loại'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon class (FontAwesome)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='Số phòng tắm'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Số phòng ngủ'),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.IntegerField(default=1, verbose_name='Số giường'),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Nhà riêng', 'Nhà riêng / nguyên căn'), ('Căn hộ', 'Căn hộ / chung cư'), ('Phòng riêng', 'Phòng riêng'), ('Biệt thự', 'Biệt thự'), ('Khách sạn / resort', 'Khách sạn / resort'), ('Nhà khách / nhà nghỉ', 'Nhà khách / nhà nghỉ'), ('Cabin / nhà gỗ', 'Cabin / nhà gỗ'), ('Tiny house', 'Tiny house'), ('Nhà trên cây', 'Nhà trên cây'), ('Nhà thuyền', 'Nhà thuyền'), ('Glamping / lều', 'Glamping / lều'), ('Nông trại / farmstay', 'Nông trại / farmstay')], default='Nhà riêng', max_length=50, verbose_name='Loại chỗ ở'),
        ),
        migrations.AddField(
            model_name='listing',
            name='usage_type',
            field=models.CharField(choices=[('Toàn bộ nhà', 'Toàn bộ nhà'), ('Phòng riêng', 'Phòng riêng'), ('Phòng chung', 'Phòng chung')], default='Toàn bộ nhà', max_length=50, verbose_name='Loại sử dụng'),
        ),
        migrations.AddField(
            model_name='reviewmedia',
            name='media_url',
            field=models.URLField(default='', max_length=255, verbose_name='Link Media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Ảnh'), ('video', 'Video')], max_length=10, verbose_name='Loại media'),
        ),
    ]
