# Generated by Django 4.2.27 on 2026-01-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_listing_cleaning_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmedia',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
