# Generated by Django 4.2.27 on 2026-01-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_reviewmedia_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewclassification',
            name='reason',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
