# Generated by Django 4.2.27 on 2026-02-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanalysis',
            name='sentiment',
            field=models.CharField(choices=[('pos', 'Tích cực'), ('neg', 'Tiêu cực'), ('neu', 'Trung tính')], max_length=10, verbose_name='Cảm xúc'),
        ),
    ]
