# Generated by Django 4.2.27 on 2026-02-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_reviewanalysis_sentiment'),
        ('app', '0032_remove_message_and_verification'),
    ]

    operations = [
    ]
