# Generated by Django 4.2.27 on 2026-02-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_merge_20260201_1530'),
        ('app', '0033_merge_20260201_1544'),
    ]

    operations = [
    ]
