# Generated by Django 4.2.27 on 2026-02-01 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_add_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('listing_approved', 'Chỗ ở được duyệt'), ('listing_rejected', 'Chỗ ở bị từ chối'), ('new_booking', 'Có đặt phòng mới'), ('booking_confirmed', 'Đặt phòng được xác nhận'), ('booking_cancelled', 'Đặt phòng bị hủy'), ('guest_checkin', 'Khách nhận phòng'), ('guest_checkout', 'Khách trả phòng'), ('booking_completed', 'Hoàn thành lượt thuê'), ('payment_received', 'Nhận thanh toán'), ('review_received', 'Nhận đánh giá mới')], max_length=30, verbose_name='Loại thông báo')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.booking', verbose_name='Đặt phòng liên quan')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.listing', verbose_name='Chỗ ở liên quan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
