# Generated by Django 4.2.27 on 2026-02-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_add_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmedia',
            name='media_url',
        ),
        migrations.DeleteModel(
            name='HostPolicy',
        ),
    ]
